In [7]:
import math
import numpy as np

In [2]:
A=16
print(math.sqrt(A))


4.0


In [4]:
from math import sqrt,sin
A=16
B=3.14
print(sqrt(A))
print(sin(B))

4.0
0.0015926529164868282


In [10]:
import numpy as np

In [12]:
data_new=np.array([[1,5,8,9,8],[4,8,6,3,7]])

In [14]:
data_new.ravel()


array([1, 5, 8, 9, 8, 4, 8, 6, 3, 7])

In [18]:
data_new.reshape()

array([[1, 5, 8, 9, 8],
       [4, 8, 6, 3, 7]])

In [20]:
data_new.resize()


In [21]:
print(data_new)

[[1 5 8 9 8]
 [4 8 6 3 7]]


In [22]:
data_new


array([[1, 5, 8, 9, 8],
       [4, 8, 6, 3, 7]])

In [25]:
np.hsplit(data_new,1)

[array([[1, 5, 8, 9, 8],
        [4, 8, 6, 3, 7]])]

In [26]:
data_new1=np.array([10,45,78,96,78,20])

In [27]:
data_new2=np.array([45,78,53,42,75,86])

In [31]:
np.hstack((data_new1,data_new2))

array([10, 45, 78, 96, 78, 20, 45, 78, 53, 42, 75, 86])

In [32]:
print ("hello world")


hello world


In [33]:
first_numpy_array=np.array([1,2,3,4])

In [35]:
print first_numpy_array

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)? (1404897069.py, line 1)

In [36]:
print(first_numpy_array)

[1 2 3 4]


In [37]:
array_with_zeros=np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
array_with_ones=np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
array_with_empty=np.empty((2,3))
array_with_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#random values will be displayed
array_with_empty=np.empty((4,3))
array_with_empty

array([[ 1.31354319e-311,  3.16202013e-322,  0.00000000e+000],
       [ 0.00000000e+000,  1.08221785e-312, -8.25806224e-311],
       [ 2.67569740e+184,  6.01180155e-067,  9.52016415e-047],
       [ 8.01418504e+165,  1.67440177e-076, -8.79704927e-311]])

In [42]:
np_arange=np.arange(12)

In [43]:
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [44]:
np_arange.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
#equal space data element
np_linspace=np.linspace(0,6,3)

In [71]:
print(np_linspace)

[0. 3. 6.]


In [62]:
#array
oneD_array=np.arange(15)

In [63]:
#1D array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [66]:
#2D array
twoD_array=oneD_array.reshape((3,5))

In [67]:
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [68]:
#3D array
threeD_array=np.arange(27).reshape(3,3,3)

In [69]:
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [72]:
#Numpy array's shapes and axes


np.array(24)

array(24)

In [73]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [75]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [77]:
np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [78]:
numpy_arr=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [80]:
numpy_arr.shape

(2, 2, 4)

In [81]:
numpy_arr.size

16

In [82]:
numpy_arr.itemsize

4

In [83]:
numpy_arr.dtype

dtype('int32')

In [84]:
numpy_arr.data

In [85]:
#dimensions 
numpy_arr.ndim

3

In [89]:
#array using looping
numpy_arr1=np.array([x for x in range(1,10)])

In [90]:
numpy_arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
numpy_arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
numpy_arr1=np.array([x for x in range(1,13)])

In [95]:
numpy_arr1.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [97]:
numpy_arr1.reshape(4,3,1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [98]:
numpy_arr1.size

12

In [100]:
numpy_arr1.shape

(12,)

In [101]:
#very helpful in pandas when we dont the exact number it will convert it to 3D array
numpy_arr1.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
numpy_arr1=numpy_arr1.reshape(3,2,2)

In [103]:
print(numpy_arr1)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [105]:
numpy_arr1.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
#arithmetic operation 

In [107]:
A=np.array([[1,2,1],[2,2,3]])
B=np.array([3,4,5])

In [109]:
A

array([[1, 2, 1],
       [2, 2, 3]])

In [110]:
B

array([3, 4, 5])

In [111]:
A+B

array([[4, 6, 6],
       [5, 6, 8]])

In [112]:
A-B

array([[-2, -2, -4],
       [-1, -2, -2]])

In [113]:
A*B

array([[ 3,  8,  5],
       [ 6,  8, 15]])

In [114]:
A/B

array([[0.33333333, 0.5       , 0.2       ],
       [0.66666667, 0.5       , 0.6       ]])

In [115]:
np.add(A,B)

array([[4, 6, 6],
       [5, 6, 8]])

In [116]:
np.power(A,2)

array([[1, 4, 1],
       [4, 4, 9]], dtype=int32)

In [117]:
np.power(B,5)

array([ 243, 1024, 3125], dtype=int32)

In [118]:
np.power(A,B)

array([[  1,  16,   1],
       [  8,  16, 243]])

In [119]:
#Conditional statements in python using (where,select)


In [120]:
x=np.array([i for i in range(10)])

In [121]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
np.where(x%2==0,'even','odd')

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd'], dtype='<U4')

In [126]:
condlist=[x>5,x<5]
choicelist=[x**2,x**3]

In [127]:
np.select(condlist,choicelist,default=100)

array([  0,   1,   8,  27,  64, 100,  36,  49,  64,  81])

In [ ]:
#

In [128]:
arr=np.array([[1,2,3],[5,8,9],[7,6,3]])

In [129]:
arr

array([[1, 2, 3],
       [5, 8, 9],
       [7, 6, 3]])

In [131]:
#it gives minimum value
np.amin(arr)

1

In [132]:
#vertical min
np.amin(arr,axis=0)

array([1, 2, 3])

In [133]:
#horizontal min
np.amin(arr,axis=1)

array([1, 5, 3])

In [134]:
#max
np.amax(arr)

9

In [135]:
np.amax(arr,axis=0)

array([7, 8, 9])

In [137]:
np.amax(arr,axis=1)

array([3, 9, 7])

In [138]:
#by using this we find many statistical data
np.mean(arr)

4.888888888888889

In [139]:
np.std(arr)

2.6434171674156266

In [140]:
np.median(arr)

5.0

In [141]:
np.var(arr)

6.987654320987654

In [143]:
np.percentile(arr,50)

5.0

In [144]:
#mathematic opt

In [145]:
deg=([0,30,45,60,90])

In [151]:
np.cos(deg)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362])

In [156]:
arr3=np.array([0.1,0.8,-2.2,-9.78])

In [157]:
np.floor(arr3)

array([  0.,   0.,  -3., -10.])

In [158]:
np.ceil(arr3)

array([ 1.,  1., -2., -9.])

In [159]:
#slicing

In [172]:
array_1d=np.array([1,2,3,4,5])
array_2d=np.array([[1,2,3],[6,5,8]])
array_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[1,2,3],[6,5,8]]])

In [161]:
array_1d[2]

3

In [162]:
array_2d[1,2]

8

In [173]:
array_3d[0,1,2]

6